ComppiProteinSearchBundle_proteinsearch:
    pattern:  /protein_search/{keyword}
    defaults: { _controller: ComppiProteinSearchBundle:ProteinSearch:proteinSearch, keyword: '' }

ComppiProteinSearchBundle_interactors:
    pattern:  /protein_search/interactors/{comppi_id}/{get_interactions}
    defaults: { _controller: ComppiProteinSearchBundle:ProteinSearch:interactors, get_interactions: 0 }
    requirements:
        id:  \d+
        
ComppiProteinSearchBundle_proteinsearch_autocomplete:
    pattern:  /protein_search/autocomplete/{keyword}
    defaults: { _controller: ComppiProteinSearchBundle:ProteinSearch:autocomplete }

ComppiProteinSearchBundle_subgraph:
    pattern:  /protein_search/subgraph/{comppi_id}
    defaults: { _controller: ComppiProteinSearchBundle:ProteinSearch:subgraph }
    requirements:
        id:  \d+