ComppiProteinSearchBundle_proteinsearch:
    pattern:  /protein_search
    defaults: { _controller: ComppiProteinSearchBundle:ProteinSearch:proteinSearch }

ComppiProteinSearchBundle_interactors:
    pattern:  /protein_search/interactors/{comppi_id}
    defaults: { _controller: ComppiProteinSearchBundle:ProteinSearch:interactors }
    requirements:
        id:  \d+
        
ComppiProteinSearchBundle_proteinsearch_autocomplete:
    pattern:  /protein_search/autocomplete/{keyword}
    defaults: { _controller: ComppiProteinSearchBundle:ProteinSearch:autocomplete }