ComppiProteinSearchBundle_proteinsearch:
    pattern:  /protein_search/{get_keyword}
    defaults: { _controller: ComppiProteinSearchBundle:ProteinSearch:proteinSearch, get_keyword: '' }

ComppiProteinSearchBundle_interactors_by_name:
    pattern:  /protein_search/interactors/{name}/{get_interactions}
    defaults: { _controller: ComppiProteinSearchBundle:ProteinSearch:interactorsByName, get_interactions: '' }
    requirements:
        name: "^[a-zA-Z][0-9a-zA-Z]{5}$"

ComppiProteinSearchBundle_interactors:
    pattern:  /protein_search/interactors/{comppi_id}/{get_interactions}
    defaults: { _controller: ComppiProteinSearchBundle:ProteinSearch:interactors, get_interactions: '' }
    requirements:
        comppi_id:  \d+

ComppiProteinSearchBundle_proteinsearch_autocomplete:
    pattern:  /protein_search/autocomplete/{keyword}
    defaults: { _controller: ComppiProteinSearchBundle:ProteinSearch:autocomplete }

ComppiProteinSearchBundle_subgraph:
    pattern:  /protein_search/subgraph/{comppi_id}
    defaults: { _controller: ComppiProteinSearchBundle:ProteinSearch:subgraph }
    requirements:
        id:  \d+