ComppiDescriptionBundle_about:
    pattern:  /home
    defaults: { _controller: ComppiDescriptionBundle:Description:About }

ComppiDescriptionBundle_impressum:
    pattern:  /impressum
    defaults: { _controller: ComppiDescriptionBundle:Description:Impressum }

ComppiDescriptionBundle_help:
    pattern:  /help/{subpage}
    defaults: { _controller: ComppiDescriptionBundle:Description:Help, subpage = '' }