ComppiDescriptionBundle_about:
    pattern:  /home
    defaults: { _controller: ComppiDescriptionBundle:Description:About }

ComppiDescriptionBundle_help:
    pattern:  /help
    defaults: { _controller: ComppiDescriptionBundle:Description:Help }

ComppiDescriptionBundle_impressum:
    pattern:  /impressum
    defaults: { _controller: ComppiDescriptionBundle:Description:Impressum }