ComppiDescriptionBundle_about:
    pattern:  /about
    defaults: { _controller: ComppiDescriptionBundle:Description:About }

ComppiDescriptionBundle_help:
    pattern:  /help
    defaults: { _controller: ComppiDescriptionBundle:Description:Help }