ComppiDescriptionBundle:
    resource: "@ComppiDescriptionBundle/Resources/config/routing.yml"
    prefix:   /
    defaults: { _controller: DescriptionBundle:Description:About }

ComppiProteinSearchBundle:
    resource: "@ComppiProteinSearchBundle/Resources/config/routing.yml"
    prefix:   /protein_search/

StatBundle:
    resource: "@StatBundle/Controller/"
    type:     annotation
    prefix:   /stat/

dev_home:
    pattern:   /
    defaults:  { _controller: DownloadBundle:Download:list }    

DownloadBundle:
    resource: "@DownloadBundle/Controller/"
    type:     annotation
    prefix:   /download/

#LoaderBundle:
#    resource: "@LoaderBundle/Controller/"
#    type:     annotation
#    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
