dev_home:
    pattern:   /
    defaults:  { _controller: StatBundle:SourceStat:index } 
    
stat_home:
    pattern:   /stat    
    defaults:  { _controller: StatBundle:SourceStat:index } 

StatBundle:
    resource: "@StatBundle/Controller/"
    type:     annotation
    prefix:   /stat/

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
