DownloadCenterBundle:
    resource: "@DownloadCenterBundle/Resources/config/routing.yml"
    prefix:   /

home:
    pattern: /
    defaults: { _controller: ComppiDescriptionBundle:Description:About }

ComppiProteinSearchBundle:
    resource: "@ComppiProteinSearchBundle/Resources/config/routing.yml"
    prefix:   /

DownloadDbBundle:
    resource: "@DownloadDbBundle/Resources/config/routing.yml"
    prefix:   /download/

ComppiDescriptionBundle:
    resource: "@ComppiDescriptionBundle/Resources/config/routing.yml"
    prefix:   /

StatBundle:
    resource: "@StatBundle/Controller/"
    type:     annotation
    prefix:   /stat/
    
stat_home:
    pattern: /stat/
    defaults: { _controller: StatBundle:SourceStat:index }    

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
