DownloadCenterBundle_downloads:
    pattern:  /downloads
    defaults: { _controller: DownloadCenterBundle:DownloadCenter:currentReleaseGui }

DownloadCenterBundle_currentrelease:
    pattern:  /downloads/current_release
    defaults: { _controller: DownloadCenterBundle:DownloadCenter:currentReleaseGui }

DownloadCenterBundle_currentrelease:
    pattern:  /downloads/current_release
    defaults: { _controller: DownloadCenterBundle:DownloadCenter:currentReleaseGui }

DownloadCenterBundle_previousreleases:
    pattern:  /downloads/previous_releases
    defaults: { _controller: DownloadCenterBundle:DownloadCenter:previousReleasesGui }

DownloadCenterBundle_getpreviousrelease:
    pattern:  /downloads/get_previous_release/{file}
    defaults: { _controller: DownloadCenterBundle:DownloadCenter:previousRelease }