DownloadCenterBundle_downloads:
    pattern:  /downloads
    defaults: { _controller: DownloadCenterBundle:DownloadCenter:downloadCenter }

DownloadCenterBundle_getrelease:
    pattern:  /downloads/get_release/{file}
    defaults: { _controller: DownloadCenterBundle:DownloadCenter:serveRelease }