parameters:
#    download_center.example.class: Comppi\DownloadCenterBundle\Example

services:
#    download_center.example:
#        class: %download_center.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
