DownloadDbBundle_download:
    pattern:  /
    defaults: { _controller: DownloadDbBundle:DownloadDb:download }

DownloadDbBundle_serve:
    pattern:  /serve
    defaults: { _controller: DownloadDbBundle:DownloadDb:serve }